name: login_register_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  spider: ^4.2.2
  google_fonts: ^4.0.0 # Check for latest version on pub.dev
  video_player: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: any
  flutter_native_splash: any


flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/videos/

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png

flutter_native_splash:
  image: assets/images/splashscreen.png
  android: true
  ios: true
  color: "#ffffff"
